### ISSUE TITLE
Output cadence 

### ISSUE THREAD

**Issue by hannorein** [matthewholman/assist#14]
Unless I'm missing something, the user has no real control over the output cadence right now. Would it make sense to allow the user to request an output at regular intervals (similar to what NASA Horizons does). This could just be an additional option. But I think we might even want to make this the default. So instead of the user defining the number of substeps as a fraction of the timestep (which is changing because IAS15 is adaptive), the user would provide a time interval they want between outputs. This would make use of the same interpolation that is currently being used in the `store_function`, just evaluating it at different points. One advantage would be that the user knows exactly how much memory needs to be allocated for the output variables.

I'm happy to implement that but I want to check if that's something you think is worth having and/or if you prefer the current substeps idea.

**Comment by matthewholman** [comment]
I like this idea, Hanno.  Most users are probably more interested in a particular output frequency than in a number of substeps.  If you are willing to implement it, that would be great!

I do think we want to have some capacity to output a flexible representation of the trajectory, such as the polynomial coefficients or sampling that tracks the variation in the length of the time step.  This will be useful for fitting observations.
