### ISSUE TITLE
jd_ref bug?

### ISSUE THREAD

**Issue by hannorein** [matthewholman/assist#16]
I'm looking into the `jd_ref` thing. But I'm confused. I'm either missing something (most likely) or there is a bug.

In the examples, both `jd_ref` and `tstart` are full (not relative) Julian dates. The rebound variable `r->t` is being set to `tstart`, so also a full Julian date. But then [this line](https://github.com/matthewholman/assist/blob/main/src/planets.c#L310) doesn't make sense. Following through the various function calls, I believe the code is just adding `jd_ref` to `r->t` here and then comparing it to `pl->beg` and `pl->end`. All of these are in full Julian dates so it doesn't work. It would only work if `r->t` is a relative Julian date. 

Maybe this specific line didn't trigger an error because the code was never tested with dates before 11 Jan 17000 CE. But I'm also not sure that the lines below are correct where the record number `blk` is calculated. But that would have surely shown up on a test, so I assume that part must be correct. So I must be missing something.

**Comment by matthewholman** [comment]
As far as I know, the variable t in the routines in assist.c and forces.c is a time relative to jd_ref.  So tstart and tend are relative to jd_ref.  I have been testing the routines with jupyter notebooks, so simplest/problem.c is probably no up to date and doesn't reflect the relatively recent switch to jd_ref and t.

**Comment by hannorein** [comment]
Ok. If simplest/problem.c is not up-to-date then, that would explain things...
