### ISSUE TITLE
Geocentric flag

### ISSUE THREAD

**Issue by hannorein** [matthewholman/assist#22]
The `geocentric` flag currently doesn't do anything at the moment. Do you plan to add some functionality in the future or can I remove it?

**Comment by matthewholman** [comment]
There is code that supports it in forces.c, but I have been tempted to remove it because it won't get used much.

**Comment by hannorein** [comment]
I'm sorry! I've missed that!

**Comment by hannorein** [comment]
Let's leave it for now.
