### ISSUE TITLE
Symbols in shared library

### ISSUE THREAD

**Issue by hannorein** [matthewholman/assist#3]
When writing a shared library, people tend to add a prefix to all non-static variables and functions to prevent collisions between symbols with the same name from different libraries. If for example rebound and assist were both implementing a function with the name `heartbeat`, then there would be a conflict. At the moment a lot of symbols in assist do not have the `assist_` prefix. You can check which ones by running:

```
nm -g --defined-only libassist.so
```

All the symbols that show up when running this command should start with `assist_`.

**Comment by matthewholman** [comment]
I added the assist_ prefix to all_ephem().  Only integration_function() remains to be fixed.

**Comment by aryaakmal** [comment]
yup

**Comment by hannorein** [comment]
Sounds good!

**Comment by matthewholman** [comment]
This is completed.   However, on the python side the function is still called integration_function().  I'll work on that later.

**Comment by hannorein** [comment]
There are still a few left, aren't there?

```
0000000000003da4 T _jpl_calc
0000000000003cf8 T _jpl_free
00000000000035c4 T _jpl_init
0000000000003ee0 T _jpl_mass
0000000000003248 T _jpl_work
0000000000002e20 T _spk_calc
0000000000002de8 T _spk_find
00000000000029e8 T _spk_free
0000000000002a70 T _spk_init
```

**Comment by matthewholman** [comment]
Those are now updated.  (Rob, I hope you don't mind.)
