### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by hannorein** [matthewholman/assist#41]
I'm trying to add a few more unit tests to make sure I'm not messing things up. For that, I'm converting the 5303 encounter from your notebook to a unit test. Two questions:

- Why do you turn off the various harmonics for this case? I
- It looks like the initial and final position in the notebook are coming from Horizons and our results differ by ~500m. Is that right? The paper mentions that we get to within 1m when comparing our results to the small body code. Can you give me the initial/final positions for that? That would make the test more stringent.

**Comment by aryaakmal** [comment]
Hi Hanno-

 While we wait for Matt's response, I note that the caption for figure 6 in
the paper says:

"The difference in the relative position differs from that of the JPL small
bodies code of only $\sim1$~m.  (The difference with JPL Horizons is
$\sim500$~m.)"

So, your results are consistent with his Horizons results. He would have to
send you Davide's initial conditions for the better agreement - I don't
have that file.

Also, I note that in the introduction to the notebook, he says that the
harmonics are all turned on, however as you note he has a comment saying
the harmonics are turned off. I wonder if the latter is just a debugging
comment he forgot to remove.  I would assume he meant to leave in all the
harmonics - but he can let us know when he sees your message.

**Comment by aryaakmal** [comment]
So, apparently Matt did try turning off some of the higher harmonics to see
if he could get better agreement with Horizons as its not clear what exam
terms they use ....

**Comment by hannorein** [comment]
I've tried with and without harmonics (now that it's easy to turn on and off!). They differ by about 10m. But given that the JPL ones differ by 500m, that's not very significant. Hence my query for clarification and/or the data to reproduce the 1m difference with regards to the small body code.

**Comment by matthewholman** [comment]
Hanno, do you see the definition of davide_end in the 5303_Ceres notebook?  That is the endpoint that Davide got with the small bodies code.  I *believe* that is with all effects turned on.   I got agreement that was < 1m.

Sometimes it is hard to figure out what is turned on with the integrator behind Horizons.  I need to edit the manuscript to clarify the 5303 experiment, as well as to highlight the distinction between the JPL small bodies (research) code and that behind Horizons.

**Comment by hannorein** [comment]
I don't see `davide_end`. Are we looking at the same notebook? https://github.com/matthewholman/assist/blob/main/jupyter_examples/5303_Ceres.ipynb

**Comment by matthewholman** [comment]
My mistake.  I was updating a different version.  Please check now.
