### ISSUE TITLE
Make asteroid SPK file optional

### ISSUE THREAD

**Issue by spenczar** [matthewholman/assist#81]
In some cases, it's not necessary for my purposes to include asteroid perturbers in the force model. But `assist_ephem_init` still requires a full small bodies ephemeris file, even if I don't intend to use it.

That's a consequential requirement because the SB441-N16 file is over 600MB, which is enough that (for example) it significantly inflates application runtime container sizes. That makes application launch time slower and causes unnecessary network traffic.

So it would be nice if I could use assist without any small bodies ephemeris file. I'm assuming that if "ASTEROIDS" is not in my set of forces, that file is not necessary, which could be wrong, though.

**Comment by matthewholman** [comment]
Yes, I believe that is correct, that you do not need the full small bodies ephemeris file if asteroid perturbers are not included in the force model.  It should fairly straightforward to make this change.
